[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
